spring.application.name=deepseek-chatbot

# Ollama
spring.ai.ollama.base-url=http://13.233.146.38:11434
spring.ai.ollama.chat.options.model=deepseek-coder:latest
spring.ai.ollama.chat.options.temperature=0.7

# Server
server.port=8085
server.address=0.0.0.0

# Logging
logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.web=DEBUG
